name: Pylint Runner
on:
  push:
    branches:
      - main

jobs:
  run-python-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pylint
        run: pip install pylint

      - name: Run Pylint with Custom Requests Rule
        run: pylint --load-plugins=custom_requests_rule your_python_script.py
